### ISSUE TITLE
Matrix multiplication fails

### ISSUE THREAD

**Issue by MaximilianJHuber** [SciML/SparsityDetection.jl#22]
```
using SparsityDetection, SparseArrays

function f(out,in)
    A = rand(length(in), length(in))
    out .= A * in
    return nothing
end

x = [1.0:10;]
out = similar(x)
f(out, x)
sparsity!(f, out, x)
```

fails with `unsupported or misplaced expression "replaceglobalref" in function recurse`.

The expected outcome is a full matrix with ones.

**Comment by shashi** [comment]
I think it needs to be added here:

https://github.com/JuliaDiffEq/SparsityDetection.jl/blob/master/src/blas.jl

**Comment by ChrisRackauckas** [comment]
Is reroute only on Hessians?

**Comment by ChrisRackauckas** [comment]
And if that's the right way to forward it, then we need to do:

https://github.com/JuliaLang/julia/blob/master/stdlib/LinearAlgebra/src/blas.jl#L13-L62

**Comment by shashi** [comment]
Some of those will be trickier... like `mul!`, so it would have to be done on a case by case basis.

**Comment by shashi** [comment]
Hmm I think it's not trickier, we can do the list, but can't really generate the code. Need to find generic alternatives which may have different argument order etc.
