### ISSUE TITLE
Zero nonzeros?

### ISSUE THREAD

**Issue by dpo** [SciML/SparsityDetection.jl#23]
This is a follow-up of #22 where I try to resolve the issue by multiplying explicitly. However, the following simple example suggests there are no nonzeros in the Jacobian:
```julia
julia> function fun!(in, out)
         out .= 3 * in
         return out
       end
fun! (generic function with 1 method)

julia> sparsity_pattern = sparsity!(fun!, input, output)
Explored path: SparsityDetection.Path(Bool[], 1)
30×30 SparseMatrixCSC{Bool,Int64} with 0 stored entries
```
We expect nonzeros on the diagonal.

**Comment by shashi** [comment]
The convention is first argument is the output, second is the input.

It works.
