### ISSUE TITLE
Jacobian sparsity detection takes a very long time and fails some times

### ISSUE THREAD

**Issue by mohdibntarek** [SciML/SparsityDetection.jl#30]
I tried the following and it took a very long time (I had to kill it):
```julia
using SparsityDetection

x = rand(3);
y = similar(x);
f(y, x) = y .= exp.(x);
jacobian_sparsity(f, y, x)
```
Interestingly, `f(y, x) = y .= x .+ 1`, `f(y, x) = y .= x .+ x`, `f(y, x) = y .= x .* x` and `f(y, x) = y .= x .^ 2` all work fine. So it seems that something is going on with `exp`. `log` also fails with some domain error when all the numbers in `x` are positive.

**Comment by shashi** [comment]
This is happening because of the branching detection kicking into action in `exp` which looks like this:

```julia
function exp(x::T) where T<:Union{Float32,Float64}
    xa = reinterpret(Unsigned, x) & ~sign_mask(T)
    xsb = signbit(x)
    # filter out non-finite arguments
    if xa > reinterpret(Unsigned, MAX_EXP(T))
        if xa >= exponent_mask(T)
            xa & significand_mask(T) != 0 && return T(NaN)
            return xsb ? T(0.0) : T(Inf) # exp(+-Inf)
        end
        x > MAX_EXP(T) && return T(Inf)
        x < MIN_EXP(T) && return T(0.0)
    end
...
end
```

If a function `exp` calls itself then that can go into an infinite loop.

**Comment by mohdibntarek** [comment]
This isn't fixed yet by the latest release.

**Comment by mohdibntarek** [comment]
Well it's fixed when using a loop, but not broadcasting.

**Comment by mohdibntarek** [comment]
@ChrisRackauckas may you reopen this? I can't do it myself for some reason.

**Comment by mohdibntarek** [comment]
Or @shashi :)
