### ISSUE TITLE
type Fixed has no field value

### ISSUE THREAD

**Issue by SteffenPL** [SciML/SparsityDetection.jl#36]
There seems to be a small typo in [jacobian.jl](https://github.com/SciML/SparsityDetection.jl/blob/a3843f71f5eeb1109dea87a7c1bd8158a3a26364/src/jacobian.jl#L141) and [hessian.jl](https://github.com/SciML/SparsityDetection.jl/blob/a3843f71f5eeb1109dea87a7c1bd8158a3a26364/src/hessian.jl#L244)
```julia                
map(arg -> arg isa Fixed ?
arg.value : tag(arg, ctx, one(TermCombination)), args)...)
```
since `Fixed` has only a field `val`. Either the type `Fixed` or these lines have to be changed.

**Comment by ChrisRackauckas** [comment]
@shashi does that thumbs up mean that the fix is easy?

**Comment by SteffenPL** [comment]
In my case, just renaming makes it work. 
I was a bit confused about how to implement the tests. That's why I didn't send a pull request yet.

https://github.com/SteffenPL/SparsityDetection.jl/commit/1c24bbe420748067fff82576482daa447b41bd78

**Comment by shashi** [comment]
Yeah I think @SteffenPL's diagnosis is correct.

Test could be just be `jacobian_sparisty(f, y,x, Fixed(z))` and `f(x,y,z) = z > 0 ? y .= x : y .= reverse(x)`

The sparsity depends on the value of `z` here and it's always a diagonal (either a identity or a reversed diagonal)

If `Fixed` did not work, then the sparsity would come from both branches making it more like an "X" (crossed diagonals)
