### ISSUE TITLE
Failure under Julia 1.7.0-beta2

### ISSUE THREAD

**Issue by j-fu** [SciML/SparsityDetection.jl#50]
Hi, 
SparsityDetection fails under 1.7.0-beta2

Here is the mwe: https://gist.github.com/j-fu/022cd00e1525269c9b6dbf256833c5c3#file-sd-mwe-jl

And this is the error message:  https://gist.github.com/j-fu/022cd00e1525269c9b6dbf256833c5c3#file-gistfile1-txt

**Comment by ChrisRackauckas** [comment]
@shashi @vchuravy do you know if Cassette is already updated?

**Comment by vchuravy** [comment]
https://github.com/JuliaRegistries/General/pull/39495
